### ISSUE TITLE
Running makefile on Windows?

### ISSUE THREAD

**Issue by hquanvo** [LeetCube/LeetCube#26]
I'm trying to find a way to run the C++ tests on Windows using VSCode. I already installed and set up mingw, got the c/c++ extension on VSC and installed make using chocolatey. Problem is that when I try to run ```make bin/test_n``` (as in the How To Run markdown file) using the terminal in VSCode, it produces the following error:

```make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.```

I'll update if I can find a solution to this. If anyone manages to run it on their Windows device that'd be great if they could share how they did it.

**Comment by dataprob** [comment]
I have a Windows surface, will try it now. Also we are going to write a doc on this after we done.

**Comment by dataprob** [comment]
This C/C++ extension pack has more. I'm trying to see if it works. https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack

**Comment by dataprob** [comment]
> This C/C++ extension pack has more. I'm trying to see if it works. https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack

nvm, this is useless. I'm installing make using chocolatey.

**Comment by dataprob** [comment]
I got `make`, but it doesn't work when I do `make bin/test_1`
![Screenshot 2023-06-02 114722](https://github.com/LeetCube/LeetCube/assets/86937926/db42e9da-242d-4523-b255-d9b5ea3bab87)

**Comment by hquanvo** [comment]
Looks like it's the same result I got when attempting to use make in the cmd prompt

**Comment by hquanvo** [comment]
I'm trying to see if it works for a local test file and doesn't look like it works either, so I'll have a look at it again after I wake up

**Comment by dataprob** [comment]
Could it be new changes blank made? I'm looking at the pr.

**Comment by dataprob** [comment]
I'm running bash shell on vscode. Now looking at cmake suggested by @william-swy 
![Screenshot 2023-06-02 121958](https://github.com/LeetCube/LeetCube/assets/86937926/acf39a5b-7230-4db5-b458-c5cee1001714)

**Comment by dataprob** [comment]
blank suggested wsl, since school server is bad, so we gonna look into that

**Comment by hquanvo** [comment]
Alright I'll try to set it up on my end, will update when stuff works

**Comment by dataprob** [comment]
I got `make clean` to work on windows, using bash shell in vscode

![Screenshot 2023-06-02 202749](https://github.com/LeetCube/LeetCube/assets/86937926/c0806f4e-c504-496f-8427-0f4a89e047da)
![Screenshot 2023-06-02 202727](https://github.com/LeetCube/LeetCube/assets/86937926/55d94777-1ffe-4a01-801b-aeefca33f9a0)

**Comment by dataprob** [comment]
Conclusion: can't `make` on Windows with choco's make. Nothingyet @hquanvo will do a write up when wsl is figured out! I'll do a write up on brew's `make` for mac.

**Comment by dataprob** [comment]
First, let's install brew on wsl
https://docs.brew.sh/Homebrew-on-Linux#:~:text=The%20Homebrew%20package%20manager%20may,if%20they%20are%20new%20enough.

**Comment by dataprob** [comment]
Once brew's there, we can try install `make`. But notice this
<img width="599" alt="Screenshot 2023-06-03 at 6 36 48 AM" src="https://github.com/LeetCube/LeetCube/assets/86937926/861a5128-7777-4cc9-a3db-e7f1bacb1388">
https://formulae.brew.sh/formula/make

**Comment by dataprob** [comment]
GitHub Codespaces
See bottom left in vscode to know if you are in codespace or local
<img width="849" alt="9-billing" src="https://github.com/LeetCube/LeetCube/assets/86937926/263bd67d-7a4e-4375-96b0-2a17f04e507c">
<img width="715" alt="10-reconnect" src="https://github.com/LeetCube/LeetCube/assets/86937926/de498b4e-ee1c-4a5a-85eb-96c87aa18bdc">
<img width="906" alt="1-create" src="https://github.com/LeetCube/LeetCube/assets/86937926/16dd25ca-b012-4bdd-850b-720451fb867c">
<img width="798" alt="2-ext" src="https://github.com/LeetCube/LeetCube/assets/86937926/3a60d9c7-c378-48a0-9c5b-dd70576c84fb">
<img width="289" alt="3-signin" src="https://github.com/LeetCube/LeetCube/assets/86937926/10485680-9e53-475e-9763-12f1c322305b">
<img width="303" alt="4-connect" src="https://github.com/LeetCube/LeetCube/assets/86937926/45df9785-1dd7-40ee-bf46-5b49dc7f985f">
<img width="304" alt="5-in" src="https://github.com/LeetCube/LeetCube/assets/86937926/2d6a511a-bc4d-4ef5-8b21-631bb44266af">
<img width="1140" alt="6-make" src="https://github.com/LeetCube/LeetCube/assets/86937926/c78cc4b1-098c-4e1d-a42c-78a9d186b840">
<img width="721" alt="7-stop" src="https://github.com/LeetCube/LeetCube/assets/86937926/788c4f59-1355-41b4-bbec-df4e37094d54">
<img width="1034" alt="8-stop-check" src="https://github.com/LeetCube/LeetCube/assets/86937926/115c5640-8abd-4382-895f-99a66565c2cf">

**Comment by hquanvo** [comment]
The codespace solution is amazing, I got everything to run like I wanted to. Since we didn't manage to figure out wsl I don't think I'm going to do a write up, unless someone else needs it.

**Comment by dataprob** [comment]
Yeah, Codespace's awesome! We abandon wsl, so don't need to do a write up. I'll do a write up on Codespaces.
