### ISSUE TITLE
diff ListNode definitions

### ISSUE THREAD

**Issue by dataprob** [LeetCube/LeetCube#31]
Seems LC has diff definitions of structures, like everyone said if we have a class ListNode, then what do we do for other versions of ListNode?

**Comment by william-swy** [comment]
The safest but most likely most repetitive version would be redefining ListNode for every question as LC could decide to change up the definition for some questions.

**Comment by dataprob** [comment]
I think LC mainly use 1 version, and we can call other versions `class ListNodeDouble` for doubly linked lists etc. Basically have a desc short name?

**Comment by dataprob** [comment]
So for example `class ListNode1` for Q1's version?

**Comment by dataprob** [comment]
Ok, so basically for each Q just copy what LC provides, which is `class ListNode` and `class Solution`. Then I guess we r done!

**Comment by dataprob** [comment]
Oh wait I discovered `python_deps` has this test helper, I guess it's fine, we'll add other classes later.
https://github.com/LeetCube/LeetCube/blob/main/python/tests/python_deps/data_structures.py

**Comment by dataprob** [comment]
Since Requiem and I deal with python, I think I'll close this issue now. Thanks everyone!
