### ISSUE TITLE
Add TS tests

### ISSUE THREAD

**Issue by PhaseRush** [LeetCube/LeetCube#34]
I've made a PR to add a ts question but I didn't make the tests yet (it was a bit annoying and I'm not the most familiar in ts!). I'm making this issue to track this for the future.

**Comment by dataprob** [comment]
I use chai for JS testing, and I think it works for TS too. Just need `@types/chai` package in addition to chai.
https://www.chaijs.com/
https://www.npmjs.com/package/@types/chai

**Comment by dataprob** [comment]
For JS I haven't used JSON for my test cases, which I'll do. You can look at my chai tests, which contain assertions for regular and promise checking.

**Comment by dataprob** [comment]
@PhaseRush whenever you are free we can add test, or lmk I can do it too! Also file renaming!
#85
Yeah we don't need to append name for ts solus.
I see that Requiem @PhaseRush appended his `phaserush` name for [code_2631_phaserush](https://github.com/LeetCube/LeetCube/blob/main/typescript/src/code_2631_phaserush.ts), I'll open a todo.

_Originally posted by @dataprob in https://github.com/LeetCube/LeetCube/pull/85#discussion_r1248699515_

**Comment by PhaseRush** [comment]
I dont have capacity to writ these tests, feel free to take this task

**Comment by dataprob** [comment]
> I dont have capacity to writ these tests, feel free to take this task

aight will do!
