### ISSUE TITLE
Allow an optional descriptions field in test cases

### ISSUE THREAD

**Issue by william-swy** [LeetCube/LeetCube#37]
The current test case format is
```
[
    {
        "contributor": ...,
        "input": {
            "input1": ...,
            ...
        },
        "output": ...
    },
    ...
]
```

would be nice to have an optional descriptions field 
```
[
    {
        "contributor": ...,
        "description": <optional>,
        "input": {
            "input1": ...,
            ...
        },
        "output": ...
    },
    ...
]
```

so that others can see what the test case is trying to test instead of forcing others to piece together the test case by reading the problem statement, input and output.

**Comment by william-swy** [comment]
> You wanna go through every test case so far and add descs for all of them then?

I think it is fine to not add it to "all of them" as in all test cases committed. But rather keep it optional so that all previous test cases are still considered "valid format".

**Comment by dataprob** [comment]
Great work keep it up!
