### ISSUE TITLE
Decide on a LICENSE

### ISSUE THREAD

**Issue by PhaseRush** [LeetCube/LeetCube#45]
iirc, by default, no license means that the repo is copyrighted. We should deciding on a License so we can be explicit about that, or clarify our stance.

There are two main licenses I think we can choose:

[MIT](https://choosealicense.com/licenses/mit/).

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

[GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)

> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.

I'm ok with either one. We can put up a poll to decide.

**Comment by PhaseRush** [comment]
@LeetCube/team Tagging for visibility.

**Comment by dataprob** [comment]
MIT, seems no one objects, so I'll add it!
