### ISSUE TITLE
Choose your role

### ISSUE THREAD

**Issue by dataprob** [LeetCube/LeetCube#5]
Currently everyone besides me has **write** role, so choose your role by commenting below!

- [ ] Write: Recommended for contributors who actively push to your project
- [ ] Maintain: Recommended for project managers who need to manage the repository without access to sensitive or destructive actions
- [ ] Admin: Recommended for people who need full access to the project, including sensitive and destructive actions like managing security or deleting a repository

**Comment by hquanvo** [comment]
write

**Comment by ysaleh03** [comment]
write

**Comment by Hgjnnf** [comment]
Write

**Comment by ryanmckim** [comment]
write

**Comment by PhaseRush** [comment]
write

**Comment by dataprob** [comment]
default to **write** privilege for Jason and Eric

**Comment by dataprob** [comment]
So Annie has **admin** access, and everyone else has **write** access!
